### ISSUE TITLE
Plugin incompatible with Gradle 8

### ISSUE THREAD

**Issue by anandsathe67** [BranchMetrics/capacitor-branch-deep-links#109]
### Describe the bug

As part of the Capacitor 5 upgrade, I switched my Android setup to use Gradle 8. Am unable to compile the project due to incompatibility of this plugin with gradle 8 (works fine with gradle 7.x)

### Steps to reproduce

1. Specify gradle 8.0.2 in build.gradle
2. Try to build your project which uses this plugin
3. The following error is seen in the build log
Seeing this in the log while building my project:
`A problem occurred configuring project ':capacitor-branch-deep-links'.
> defaultConfig contains custom BuildConfig fields, but the feature is disabled.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':capacitor-branch-deep-links'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:84)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:77)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$400(LifecycleProjectEvaluator.java:55)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate.run(LifecycleProjectEvaluator.java:255)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.lambda$run$0(LifecycleProjectEvaluator.java:114)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.lambda$applyToMutableState$0(DefaultProjectStateRegistry.java:388)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.lambda$fromMutableState$1(DefaultProjectStateRegistry.java:411)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withReplacedLocks(DefaultWorkerLeaseService.java:345)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.fromMutableState(DefaultProjectStateRegistry.java:411)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.applyToMutableState(DefaultProjectStateRegistry.java:387)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.run(LifecycleProjectEvaluator.java:100)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:72)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:792)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:156)
	at ....`

### Expected behavior

The project should build without any errors

### SDK Version

5.0.0

### Make and Model

Oppo A74

### OS

Android 13

### Additional Information/Context

Using Android Studio Flamingo | 2022.2.1 Patch 2

**Comment by nvahalik** [comment]
@anandsathe67 We have been able to get this running (at least so far) successfully in Capacitor 5 for both iOS and Android using our repo here: 

    https://github.com/1stphorm/capacitor-branch-deep-links/tree/cap-5-branch-sdk

To try it out, you can run:

    npm i https://github.com/1stphorm/capacitor-branch-deep-links\#cap-5-branch-sdk

This branch also updates from the original `Branch` module for iOS to use the new `BranchSDK` module.

**Comment by avisiboni** [comment]
@nvahalik  I tried your suggestion, and receive the following error: 
<img width="1015" alt="image" src="https://github.com/BranchMetrics/capacitor-branch-deep-links/assets/11908703/937a3d58-0c63-4d61-8bdb-eab3dca89e6d">
I'll appreciate your help, thanks!

**Comment by nvahalik** [comment]
Not sure why it is doing SSH... That seems like an NPM problem perhaps?

**Comment by anandsathe67** [comment]
Here is the patch I had to use to make it work with gradle 8 (added namespace)

```
diff --git a/node_modules/capacitor-branch-deep-links/android/build.gradle b/node_modules/capacitor-branch-deep-links/android/build.gradle
index 85ae5be..524f9fa 100644
--- a/node_modules/capacitor-branch-deep-links/android/build.gradle
+++ b/node_modules/capacitor-branch-deep-links/android/build.gradle
@@ -25,6 +25,7 @@ buildscript {
 apply plugin: 'com.android.library'
 
 android {
+    namespace "co.boundstate.capacitorbranchdeeplinks"
     compileSdkVersion project.hasProperty('compileSdkVersion') ? rootProject.ext.compileSdkVersion : 32
     defaultConfig {
         minSdkVersion project.hasProperty('minSdkVersion') ? rootProject.ext.minSdkVersion : 22
@@ -32,7 +33,6 @@ android {
         versionCode 1
         versionName "1.0"
         testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
-        buildConfigField("String", "CAPACITOR_BRANCH_VERSION", "\"${getNpmVersion()}\"")
     }
     buildTypes {
         release {

diff --git a/node_modules/capacitor-branch-deep-links/android/src/main/AndroidManifest.xml b/node_modules/capacitor-branch-deep-links/android/src/main/AndroidManifest.xml
index 4c290b0..e546d9a 100644
--- a/node_modules/capacitor-branch-deep-links/android/src/main/AndroidManifest.xml
+++ b/node_modules/capacitor-branch-deep-links/android/src/main/AndroidManifest.xml
@@ -1,5 +1,5 @@
 
   <manifest xmlns:android="http://schemas.android.com/apk/res/android"
-      package="co.boundstate.capacitorbranchdeeplinks">
+      >
   </manifest>
   
\ No newline at end of file
diff --git a/node_modules/capacitor-branch-deep-links/android/src/main/java/co/boundstate/BranchDeepLinks.java b/node_modules/capacitor-branch-deep-links/android/src/main/java/co/boundstate/BranchDeepLinks.java
index 464980a..bc45c72 100644
--- a/node_modules/capacitor-branch-deep-links/android/src/main/java/co/boundstate/BranchDeepLinks.java
+++ b/node_modules/capacitor-branch-deep-links/android/src/main/java/co/boundstate/BranchDeepLinks.java
@@ -6,7 +6,7 @@ import android.net.Uri;
 import android.os.UserManager;
 import android.util.Base64;
 import androidx.annotation.NonNull;
-import co.boundstate.capacitorbranchdeeplinks.BuildConfig;
+import co.boundstate.capacitorbranchdeeplinks.*;
 import com.getcapacitor.JSArray;
 import com.getcapacitor.JSObject;
 import com.getcapacitor.Plugin;
@@ -40,7 +40,7 @@ public class BranchDeepLinks extends Plugin {
     private static final String EVENT_INIT_ERROR = "initError";
 
     public static Branch getBranchInstance(@NonNull Context context) {
-        Branch.registerPlugin("Capacitor", BuildConfig.CAPACITOR_BRANCH_VERSION);
+        Branch.registerPlugin("Capacitor", "5.0.0");
 
         boolean isUnlocked = isUserUnlocked(context);
 

```

**Comment by gdeluna-branch** [comment]
We'll be updating our plugin to cap 5 as well as updating to gradle 8. Will close this out as soon as we have it published.

**Comment by GiannisS** [comment]
> We'll be updating our plugin to cap 5 as well as updating to gradle 8. Will close this out as soon as we have it published.

Thanks for the feedback. Is there an ETA for this?

**Comment by gdeluna-branch** [comment]
We expect by this Friday, pending testing.

**Comment by gdeluna-branch** [comment]
Please test capacitor 5 with this Branch Capacitor beta package https://www.npmjs.com/package/capacitor-branch-deep-links/v/6.0.0-beta.0

For iOS you will need to import `BranchSDK` instead of `Branch`. 
There should not be any other code changes needed for Android.

Let me know if this package works out, we'll release proper next week with documentation updates.

**Comment by anandsathe67** [comment]
Hello,
Do you think it might make sense to use the latest gradle (8.2) ? Might as
well be on the latest version if we are releasing it now
Regards
Anand

**Comment by GiannisS** [comment]
While building in android studio i get this error: 

```
error: cannot find symbol
import androidx.multidex.MultiDex;
                        ^
  symbol:   class MultiDex
  location: package androidx.multidex
  ```
  
  my CustomApplicationClass.java
  
  looks like this
  
  ```
  package (my package name);

import android.content.Context;
import android.os.UserManager;
import androidx.multidex.MultiDex;
import androidx.multidex.MultiDexApplication;
import static android.os.Build.VERSION.SDK_INT;
import io.branch.referral.Branch;

public class CustomApplicationClass extends MultiDexApplication {

  @Override
  public void onCreate() {
    super.onCreate();
     // Branch logging for debugging
     Branch.enableLogging();

    if (SDK_INT >= 24) {
      UserManager um = getApplicationContext().getSystemService(UserManager.class);
      if (um == null || !um.isUserUnlocked()) return;
    }

    // Branch object initialization
    Branch.getAutoInstance(this);
  }

  @Override
  protected void attachBaseContext(Context base) {
    super.attachBaseContext(base);
    MultiDex.install(this);
  }
 }

```

in my `build.gradle` I have `multiDexEnabled true` and `implementation 'com.android.support:multidex:1.0.3'`

**Comment by gdeluna-branch** [comment]
Published https://www.npmjs.com/package/capacitor-branch-deep-links/v/6.0.0
https://github.com/BranchMetrics/capacitor-branch-deep-links/releases/tag/v6.0.0
