### ISSUE TITLE
Issue with version 3.0.0

### ISSUE THREAD

**Issue by paulstelzer** [BranchMetrics/capacitor-branch-deep-links#23]
After updating to Version 3.0.0 of the capacitor plugin, I always get the following error:

```
Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$1.run(Bridge.java:526)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
        at io.branch.referral.BranchUrlBuilder.<init>(BranchUrlBuilder.java:56)
        at io.branch.referral.BranchShortLinkBuilder.<init>(BranchShortLinkBuilder.java:15)
```

I adjusted my app like mentioned in the Android setup: https://github.com/BranchMetrics/capacitor-branch-deep-links#android-setup

**Comment by tafelnl** [comment]
It could probably happen when calling one or more of the following methods: `showShareSheet`, `generateShortUrl` and `sendBranchEvent`. These methods do not necessarily make sure to instantiate the activity variable.

It is because of this commit: https://github.com/BranchMetrics/capacitor-branch-deep-links/commit/0dbd39950448b85752131595a407340cbf493bdc#diff-7dcd608548c6c4277db3aa21fca44b202ff712b42548c381870ce930e3262659

You can see `this.activity = getActivity();` has been deleted. So adding that will indeed fix the issue. Feel free to make a pull request for this. Branch will probably merge it sometime in the future.
